# Generated by Django 2.2.17 on 2021-02-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ClassName')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('cd', models.IntegerField()),
                ('explain', models.CharField(max_length=100)),
                ('on_use', models.CharField(max_length=100)),
                ('on_duration', models.CharField(max_length=100)),
                ('radius', models.CharField(max_length=100)),
                ('buff_type', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Spec')),
            ],
        ),
    ]
