# Generated by Django 2.2.17 on 2021-02-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='kind',
            field=models.CharField(default='бурст', max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='buff_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='cd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='explain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='on_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='on_use',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='radius',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
