# Generated by Django 2.2.17 on 2021-02-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210202_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='explain',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='spell',
            name='image',
            field=models.CharField(default='/static/main/images/', max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='spell',
            name='on_duration',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='spell',
            name='on_use',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='spell',
            name='tier',
            field=models.CharField(default='Базовая способность', max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='type',
            field=models.CharField(default='Инстант', max_length=100),
        ),
    ]
