# Generated by Django 2.2.17 on 2021-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210202_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slang', models.CharField(max_length=100)),
                ('original', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='spec',
            name='image',
            field=models.CharField(default='/static/main/images/', max_length=100),
        ),
    ]
