# Generated by Django 2.2.17 on 2021-02-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210203_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diminishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Стан'), (2, 'Паралич'), (3, 'Ослепление'), (4, 'Обездвиживание'), (5, 'Немота')], default=1, max_length=100)),
                ('klass', models.CharField(choices=[('Воин', 'Воин'), ('Паладин', 'Паладин'), ('Рыцарь смерти', 'Рыцарь смерти'), ('Охотник', 'Охотник'), ('Шаман', 'Шаман'), ('Охотник на демонов', 'Охотник на демонов'), ('Друид', 'Друид'), ('Разбойник', 'Разбойник'), ('Монах', 'Монах'), ('Маг', 'Маг'), ('Жрец', 'Жрец'), ('Чернокнижник', 'Чернокнижник')], default='Воин', max_length=100)),
                ('ability', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
