# Generated by Django 2.2.17 on 2021-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_diminishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diminishing',
            name='klass',
            field=models.CharField(choices=[('Воин', 'Воин'), ('Паладин', 'Паладин'), ('Рыцарь смерти', 'Рыцарь смерти'), ('Охотник', 'Охотник'), ('Шаман', 'Шаман'), ('Охотник на демонов', 'Охотник на демонов'), ('Друид', 'Друид'), ('Разбойник', 'Разбойник'), ('Монах', 'Монах'), ('Маг', 'Маг'), ('Жрец', 'Жрец'), ('Чернокнижник', 'Чернокнижник'), ('Расовая способность', 'Расовая способность')], default='Воин', max_length=100),
        ),
        migrations.AlterField(
            model_name='diminishing',
            name='type',
            field=models.CharField(choices=[('1', 'Стан'), ('2', 'Паралич'), ('3', 'Ослепление'), ('4', 'Обездвиживание'), ('5', 'Немота')], default='1', max_length=100),
        ),
    ]
